
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://59.110.239.154:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
      restart:
        enabled: true